select
    id as claim_transaction_id,
    claimid as claim_id,
    chargeid as charge_id,
    patientid as patient_id,
    type as transaction_type,
    {{ cast_to_double("amount") }} as amount,
    method as payment_method,
    {{ cast_to_timestamp("fromdate") }} as service_start_at,
    {{ cast_to_timestamp("todate") }} as service_end_at,
    placeofservice as place_of_service,
    procedurecode as procedure_code,
    modifier1, modifier2,
    diagnosisref1, diagnosisref2, diagnosisref3, diagnosisref4,
    cast({{ adapter.quote('units') }} as int) as units,
    departmentid as department_id,
    notes,
    {{ cast_to_double("unitamount") }} as unit_amount,
    transferoutid as transfer_out_id,
    transfertype as transfer_type,
    {{ cast_to_double("payments") }} as payments,
    {{ cast_to_double("adjustments") }} as adjustments,
    {{ cast_to_double("outstanding") }} as outstanding,
    appointmentid as encounter_id,
    patientinsuranceid as patient_insurance_id,
    providerid as provider_id,
    supervisingproviderid as supervising_provider_id,
    {{ cast_to_timestamp("_ingested_at") }} as ingested_at,
    _source_system as source_system,
    _row_hash as row_hash
{{ stream_read_synthea_csv('claims_transactions.csv') }}
