#!/usr/bin/env python3
"""Generate dbt schema YAML with model and column descriptions."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

COL_DESC: dict[str, str] = {
    "patient_id": "Unique patient identifier (Synthea UUID).",
    "encounter_id": "Unique clinical encounter identifier.",
    "provider_id": "Unique provider identifier.",
    "organization_id": "Unique healthcare organization or facility identifier.",
    "payer_id": "Unique insurance payer identifier.",
    "claim_id": "Unique claim header identifier.",
    "claim_transaction_id": "Unique claim financial transaction line identifier.",
    "care_plan_id": "Unique care plan identifier.",
    "imaging_study_id": "Unique imaging study identifier.",
    "member_id": "Insurance member identifier on the payer plan.",
    "charge_id": "Charge identifier associated with the transaction line.",
    "department_id": "Billing department identifier.",
    "secondary_payer_id": "Secondary payer identifier when coordination of benefits applies.",
    "primary_insurance_id": "Primary insurance coverage identifier on the claim.",
    "secondary_insurance_id": "Secondary insurance coverage identifier on the claim.",
    "patient_department_id": "Patient department identifier on the claim.",
    "patient_insurance_id": "Patient insurance policy identifier on the transaction.",
    "supervising_provider_id": "Supervising provider identifier on the claim or transaction.",
    "transfer_out_id": "Identifier for outbound payment transfer linkage.",
    "ingested_at": "Timestamp when the bronze record was ingested.",
    "source_system": "Upstream source system label (for example synthea).",
    "row_hash": "Deterministic hash of the source row for audit and deduplication.",
    "is_active": "True when the record has no end date and is considered active.",
    "is_alive": "True when the patient has no recorded death date.",
    "is_in_use": "True when the device record has no end timestamp.",
    "birth_date": "Patient date of birth.",
    "death_date": "Patient date of death, if recorded.",
    "first_name": "Patient given name.",
    "last_name": "Patient family name.",
    "middle_name": "Patient middle name.",
    "prefix": "Patient name prefix or title.",
    "suffix": "Patient name suffix.",
    "gender": "Patient gender.",
    "race": "Patient race category from source data.",
    "ethnicity": "Patient ethnicity category from source data.",
    "marital_status": "Patient marital status.",
    "birthplace": "Patient birthplace location string.",
    "address": "Street address.",
    "city": "City name.",
    "state": "State or region code.",
    "county": "County name.",
    "zip": "Postal or ZIP code.",
    "fips": "Federal Information Processing Standards county code.",
    "latitude": "Geographic latitude in decimal degrees.",
    "longitude": "Geographic longitude in decimal degrees.",
    "phone": "Contact phone number.",
    "annual_income": "Estimated annual household income.",
    "lifetime_healthcare_expenses": "Lifetime healthcare expenses attributed to the patient.",
    "lifetime_coverage_amount": "Lifetime insurance coverage amount attributed to the patient.",
    "age_years": "Patient age in whole years at reference date or death.",
    "age_band": "Patient age segment (pediatric, adult, senior, or deceased).",
    "encounter_start_at": "Encounter start timestamp.",
    "encounter_end_at": "Encounter end timestamp.",
    "encounter_start_date": "Encounter start date.",
    "encounter_duration_minutes": "Encounter length in minutes.",
    "encounter_class": "Encounter setting or class (for example ambulatory, emergency, inpatient).",
    "encounter_code": "Encounter type code from the source vocabulary.",
    "encounter_description": "Human-readable encounter type description.",
    "base_encounter_cost": "Base cost attributed to the encounter in source currency.",
    "total_claim_cost": "Total claim cost linked to the encounter.",
    "payer_coverage_amount": "Amount covered by insurance for the encounter or item.",
    "reason_code": "Clinical or administrative reason code.",
    "reason_description": "Human-readable reason description.",
    "provider_name": "Provider display name.",
    "specialty": "Provider clinical specialty.",
    "organization_name": "Organization or facility display name.",
    "org_city": "City of the organization location.",
    "org_state": "State of the organization location.",
    "payer_name": "Payer display name.",
    "payer_ownership": "Payer ownership or plan type classification.",
    "ownership": "Ownership classification for the payer.",
    "patient_gender": "Patient gender carried on the encounter context.",
    "patient_state": "Patient state of residence carried on the encounter context.",
    "transaction_type": "Claim transaction category (for example charge, payment, adjustment).",
    "amount": "Transaction amount in source currency.",
    "payment_method": "Payment method used on the transaction.",
    "service_start_at": "Service period start timestamp on the transaction.",
    "service_end_at": "Service period end timestamp on the transaction.",
    "service_at": "Primary service timestamp on the claim.",
    "service_date": "Primary service date on the claim.",
    "place_of_service": "Place of service code on the transaction.",
    "procedure_code": "Procedure or service code on the transaction or clinical record.",
    "modifier1": "First procedure modifier code.",
    "modifier2": "Second procedure modifier code.",
    "diagnosisref1": "First diagnosis reference on the transaction line.",
    "diagnosisref2": "Second diagnosis reference on the transaction line.",
    "diagnosisref3": "Third diagnosis reference on the transaction line.",
    "diagnosisref4": "Fourth diagnosis reference on the transaction line.",
    "diagnosis1": "Primary diagnosis code on the claim.",
    "diagnosis2": "Secondary diagnosis code on the claim.",
    "diagnosis3": "Tertiary diagnosis code on the claim.",
    "diagnosis4": "Fourth diagnosis code on the claim.",
    "diagnosis5": "Fifth diagnosis code on the claim.",
    "diagnosis6": "Sixth diagnosis code on the claim.",
    "diagnosis7": "Seventh diagnosis code on the claim.",
    "diagnosis8": "Eighth diagnosis code on the claim.",
    "units": "Service units billed on the transaction.",
    "unit_amount": "Per-unit amount on the transaction.",
    "notes": "Free-text notes on the transaction line.",
    "payments": "Payments applied on the transaction line.",
    "adjustments": "Adjustments applied on the transaction line.",
    "outstanding": "Outstanding balance on the transaction line.",
    "transfer_type": "Transfer type classification for payment movement.",
    "status_primary": "Primary payer claim status.",
    "status_secondary": "Secondary payer claim status.",
    "status_patient": "Patient responsibility claim status.",
    "outstanding_primary": "Outstanding balance for the primary payer.",
    "outstanding_secondary": "Outstanding balance for the secondary payer.",
    "outstanding_patient": "Outstanding patient responsibility balance.",
    "illness_onset_at": "Illness onset timestamp associated with the claim.",
    "condition_start_date": "Condition onset date.",
    "condition_end_date": "Condition resolution date, if recorded.",
    "code_system": "Vocabulary system for the clinical or billing code.",
    "condition_code": "Diagnosis or condition code.",
    "condition_description": "Human-readable condition description.",
    "procedure_start_at": "Procedure start timestamp.",
    "procedure_end_at": "Procedure end timestamp.",
    "procedure_description": "Human-readable procedure description.",
    "base_cost": "Base cost for the clinical or supply event.",
    "observation_at": "Observation collection timestamp.",
    "observation_category": "Observation category (for example vital-signs, laboratory).",
    "observation_code": "Observation code from the source vocabulary.",
    "observation_description": "Human-readable observation description.",
    "observation_value": "Observation result value as captured in source.",
    "observation_value_numeric": "Numeric observation result when parseable.",
    "value_type": "Observation value data type from source.",
    "medication_start_at": "Medication period start timestamp.",
    "medication_end_at": "Medication period end timestamp.",
    "medication_code": "Medication product code.",
    "medication_description": "Human-readable medication description.",
    "dispenses": "Number of dispense events for the medication order.",
    "total_cost": "Total medication cost for the order.",
    "immunization_at": "Immunization administration timestamp.",
    "immunization_code": "Immunization product code.",
    "immunization_description": "Human-readable immunization description.",
    "allergy_start_date": "Allergy or intolerance onset date.",
    "allergy_end_date": "Allergy or intolerance resolution date, if recorded.",
    "allergy_code": "Allergy substance or product code.",
    "allergy_description": "Human-readable allergy description.",
    "allergy_type": "Allergy record type (for example allergy, intolerance).",
    "allergy_category": "Allergy category (for example food, medication, environment).",
    "care_plan_start_date": "Care plan start date.",
    "care_plan_end_date": "Care plan end date, if recorded.",
    "care_plan_code": "Care plan type code.",
    "care_plan_description": "Human-readable care plan description.",
    "device_start_at": "Device usage start timestamp.",
    "device_end_at": "Device usage end timestamp.",
    "device_code": "Medical device code.",
    "device_description": "Human-readable device description.",
    "device_udi": "Unique device identifier (UDI).",
    "supply_date": "Supply usage date.",
    "supply_code": "Supply product code.",
    "supply_description": "Human-readable supply description.",
    "quantity": "Quantity of supplies used.",
    "study_at": "Imaging study timestamp.",
    "series_uid": "DICOM series unique identifier.",
    "bodysite_code": "Imaged body site code.",
    "bodysite_description": "Human-readable body site description.",
    "modality_code": "Imaging modality code.",
    "modality_description": "Human-readable imaging modality description.",
    "instance_uid": "DICOM instance unique identifier.",
    "sop_code": "DICOM SOP class code.",
    "sop_description": "Human-readable SOP class description.",
    "coverage_start_at": "Insurance coverage period start timestamp.",
    "coverage_end_at": "Insurance coverage period end timestamp.",
    "coverage_start_date": "Insurance coverage period start date.",
    "coverage_end_date": "Insurance coverage period end date.",
    "plan_ownership": "Insurance plan ownership classification.",
    "owner_name": "Insurance plan owner or sponsor name.",
    "amount_covered": "Total amount covered by the payer.",
    "amount_uncovered": "Total amount not covered by the payer.",
    "revenue": "Reported payer or organization revenue.",
    "covered_encounters": "Count of encounters covered by the payer.",
    "uncovered_encounters": "Count of encounters not covered by the payer.",
    "unique_customers": "Distinct customer count for the payer.",
    "quality_of_life_avg": "Average quality-of-life score for payer members.",
    "member_months": "Total member months for the payer population.",
    "utilization": "Reported organization utilization metric from source.",
    "lifetime_encounters": "Lifetime encounter count attributed to the provider.",
    "lifetime_procedures": "Lifetime procedure count attributed to the provider.",
    "active_condition_count": "Count of active conditions for the patient.",
    "active_condition_descriptions": "Set of active condition descriptions for the patient.",
    "condition_count": "Count of conditions linked to the encounter.",
    "procedure_count": "Count of procedures linked to the encounter.",
    "procedure_cost": "Total procedure cost linked to the encounter.",
    "observation_count": "Count of observations linked to the encounter.",
    "medication_count": "Count of medication orders linked to the encounter.",
    "medication_cost": "Total medication cost linked to the encounter.",
    "immunization_count": "Count of immunizations linked to the encounter.",
    "transaction_line_count": "Number of financial transaction lines for the claim.",
    "total_charges": "Sum of charge amounts for the claim.",
    "total_payments": "Sum of payment amounts for the claim.",
    "total_transfer_out": "Sum of outbound transfer amounts for the claim.",
    "total_transfer_in": "Sum of inbound transfer amounts for the claim.",
    "max_outstanding": "Maximum outstanding balance observed on claim transactions.",
    "first_service_date": "Earliest service date on claim transactions.",
    "last_service_date": "Latest service date on claim transactions.",
    "net_balance": "Net financial balance after charges, payments, and transfers.",
    "encounter_count": "Count of encounters in the aggregation grain.",
    "distinct_patients": "Count of distinct patients in the aggregation grain.",
    "distinct_providers": "Count of distinct providers in the aggregation grain.",
    "distinct_encounter_classes": "Count of distinct encounter classes experienced by the patient.",
    "distinct_claims": "Count of distinct claims in the aggregation grain.",
    "patient_count": "Count of distinct patients in the aggregation grain.",
    "first_encounter_date": "Earliest encounter date for the patient.",
    "last_encounter_date": "Most recent encounter date for the patient.",
    "total_encounter_claim_cost": "Total claim cost across patient encounters.",
    "total_base_encounter_cost": "Total base encounter cost across patient encounters.",
    "claim_count": "Count of claims for the patient or aggregation grain.",
    "lifetime_charges": "Lifetime charge amount for the patient.",
    "lifetime_payments": "Lifetime payment amount for the patient.",
    "avg_encounter_minutes": "Average encounter duration in minutes.",
    "reported_utilization": "Utilization metric reported in the organization source record.",
    "total_payer_coverage_on_encounters": "Total payer coverage amount across encounters.",
    "total_medication_coverage": "Total payer medication coverage amount.",
    "alive_count": "Count of living patients in the cohort.",
    "avg_age": "Average age of patients in the cohort.",
    "avg_lifetime_expenses": "Average lifetime healthcare expenses in the cohort.",
    "avg_annual_income": "Average annual income in the cohort.",
    "line_count": "Count of transaction lines in the aggregation grain.",
    "total_amount": "Total transaction amount in the aggregation grain.",
    "record_count": "Total number of source records in the aggregation grain.",
    "active_record_count": "Count of active source records in the aggregation grain.",
    "prescription_count": "Count of medication prescriptions in the aggregation grain.",
    "avg_dispenses": "Average dispense count per medication code.",
    "dose_count": "Count of immunization doses administered.",
    "avg_duration_minutes": "Average encounter duration in minutes for the aggregation grain.",
    "avg_claim_cost": "Average claim cost for the aggregation grain.",
    "instance_count": "Count of imaging instances in the aggregation grain.",
    "total_outstanding": "Total outstanding balance in the aggregation grain.",
    "avg_outstanding": "Average outstanding balance in the aggregation grain.",
    "recency_rank": "Recency rank where 1 is the latest reading per patient and code.",
    "pct_of_encounters": "Percentage share of total encounters for the encounter class.",
    "encounter_volume_rank": "Rank of encounter class by volume (1 is highest).",
    "avg_amount_per_line": "Average transaction amount per line.",
    "pct_of_network_amount": "Percentage share of total network transaction amount.",
    "amount_rank": "Rank by absolute transaction amount (1 is largest).",
    "provider_specialty": "Clinical specialty of the encounter provider.",
    "units": "Unit of measure for the observation result.",
    "service_date": "Service date derived from the claim or transaction.",
    "total_cost": "Total cost amount for the aggregated clinical or financial grain.",
    "total_payer_coverage": "Total payer coverage amount for the aggregated medication grain.",
}

MODELS: list[dict] = json.loads(r"""
[
  {"name":"stg_allergies","layer":"staging","tags":"{\"layer\":\"silver\",\"dbt_layer\":\"staging\",\"domain\":\"Clinical\"}","purpose":"Cleans and standardizes raw allergy records from Postgres with typed columns and an active-status flag.","columns":["allergy_start_date","allergy_end_date","patient_id","encounter_id","allergy_code","code_system","allergy_description","allergy_type","allergy_category","is_active","ingested_at","source_system","row_hash"]},
  {"name":"stg_supplies","layer":"staging","tags":"{\"layer\":\"silver\",\"dbt_layer\":\"staging\",\"domain\":\"Operations\"}","purpose":"Stages supply usage events with renamed keys and typed dates and quantities.","columns":["supply_date","patient_id","encounter_id","supply_code","supply_description","quantity","ingested_at","source_system","row_hash"]},
  {"name":"stg_providers","layer":"staging","tags":"{\"layer\":\"silver\",\"dbt_layer\":\"staging\",\"domain\":\"Operations\"}","purpose":"Stages provider master data with renamed identifiers, geolocation, and lifetime activity counts.","columns":["provider_id","organization_id","provider_name","gender","specialty","address","city","state","zip","latitude","longitude","lifetime_encounters","lifetime_procedures","ingested_at","source_system","row_hash"],"tests":{"provider_id":["unique","not_null"]}},
  {"name":"stg_procedures","layer":"staging","tags":"{\"layer\":\"silver\",\"dbt_layer\":\"staging\",\"domain\":\"Clinical\"}","purpose":"Stages clinical procedure events with standardized timestamps, codes, and costs.","columns":["procedure_start_at","procedure_end_at","patient_id","encounter_id","code_system","procedure_code","procedure_description","base_cost","reason_code","reason_description","ingested_at","source_system","row_hash"]},
  {"name":"stg_payers","layer":"staging","tags":"{\"layer\":\"silver\",\"dbt_layer\":\"staging\",\"domain\":\"Revenue cycle\"}","purpose":"Stages payer and insurer attributes with financial and membership aggregates.","columns":["payer_id","payer_name","ownership","amount_covered","amount_uncovered","revenue","covered_encounters","uncovered_encounters","unique_customers","quality_of_life_avg","member_months","ingested_at","source_system","row_hash"],"tests":{"payer_id":["unique","not_null"]}},
  {"name":"stg_payer_transitions","layer":"staging","tags":"{\"layer\":\"silver\",\"dbt_layer\":\"staging\",\"domain\":\"Revenue cycle\"}","purpose":"Stages patient insurance coverage transition periods and plan ownership.","columns":["patient_id","member_id","coverage_start_at","coverage_end_at","payer_id","secondary_payer_id","plan_ownership","owner_name","ingested_at","source_system","row_hash"]},
  {"name":"stg_patients","layer":"staging","tags":"{\"layer\":\"silver\",\"dbt_layer\":\"staging\",\"domain\":\"Patient\"}","purpose":"Stages patient demographics and socioeconomic attributes with renamed and typed fields.","columns":["patient_id","birth_date","death_date","prefix","first_name","middle_name","last_name","suffix","marital_status","race","ethnicity","gender","birthplace","address","city","state","county","fips","zip","latitude","longitude","lifetime_healthcare_expenses","lifetime_coverage_amount","annual_income","ingested_at","source_system","row_hash"],"tests":{"patient_id":["unique","not_null"]}},
  {"name":"stg_organizations","layer":"staging","tags":"{\"layer\":\"silver\",\"dbt_layer\":\"staging\",\"domain\":\"Operations\"}","purpose":"Stages healthcare organization master data with location and utilization metrics.","columns":["organization_id","organization_name","address","city","state","zip","latitude","longitude","phone","revenue","utilization","ingested_at","source_system","row_hash"],"tests":{"organization_id":["unique","not_null"]}},
  {"name":"stg_observations","layer":"staging","tags":"{\"layer\":\"silver\",\"dbt_layer\":\"staging\",\"domain\":\"Clinical\"}","purpose":"Stages clinical observations such as labs and vitals with trimmed categories and typed timestamps.","columns":["observation_at","patient_id","encounter_id","observation_category","observation_code","observation_description","observation_value","units","value_type","ingested_at","source_system","row_hash"]},
  {"name":"stg_medications","layer":"staging","tags":"{\"layer\":\"silver\",\"dbt_layer\":\"staging\",\"domain\":\"Clinical\"}","purpose":"Stages medication prescriptions with costs, coverage, and an active-status flag.","columns":["medication_start_at","medication_end_at","patient_id","payer_id","encounter_id","medication_code","medication_description","base_cost","payer_coverage_amount","dispenses","total_cost","reason_code","reason_description","is_active","ingested_at","source_system","row_hash"]},
  {"name":"stg_immunizations","layer":"staging","tags":"{\"layer\":\"silver\",\"dbt_layer\":\"staging\",\"domain\":\"Clinical\"}","purpose":"Stages immunization administration events with product codes and costs.","columns":["immunization_at","patient_id","encounter_id","immunization_code","immunization_description","base_cost","ingested_at","source_system","row_hash"]},
  {"name":"stg_imaging_studies","layer":"staging","tags":"{\"layer\":\"silver\",\"dbt_layer\":\"staging\",\"domain\":\"Clinical\"}","purpose":"Stages imaging study instances with modality, body site, and DICOM identifiers.","columns":["imaging_study_id","study_at","patient_id","encounter_id","series_uid","bodysite_code","bodysite_description","modality_code","modality_description","instance_uid","sop_code","sop_description","procedure_code","ingested_at","source_system","row_hash"]},
  {"name":"stg_encounters","layer":"staging","tags":"{\"layer\":\"silver\",\"dbt_layer\":\"staging\",\"domain\":\"Operations\"}","purpose":"Stages patient encounter events with class, cost, and linked entity foreign keys.","columns":["encounter_id","encounter_start_at","encounter_end_at","patient_id","organization_id","provider_id","payer_id","encounter_class","encounter_code","encounter_description","base_encounter_cost","total_claim_cost","payer_coverage_amount","reason_code","reason_description","ingested_at","source_system","row_hash"],"tests":{"encounter_id":["unique","not_null"],"patient_id":["not_null"]}},
  {"name":"stg_devices","layer":"staging","tags":"{\"layer\":\"silver\",\"dbt_layer\":\"staging\",\"domain\":\"Clinical\"}","purpose":"Stages medical device usage records with UDI and in-use status.","columns":["device_start_at","device_end_at","patient_id","encounter_id","device_code","device_description","device_udi","is_in_use","ingested_at","source_system","row_hash"]},
  {"name":"stg_conditions","layer":"staging","tags":"{\"layer\":\"silver\",\"dbt_layer\":\"staging\",\"domain\":\"Clinical\"}","purpose":"Stages diagnosis and condition records with an active-status flag derived from end date.","columns":["condition_start_date","condition_end_date","patient_id","encounter_id","code_system","condition_code","condition_description","is_active","ingested_at","source_system","row_hash"]},
  {"name":"stg_claims_transactions","layer":"staging","tags":"{\"layer\":\"silver\",\"dbt_layer\":\"staging\",\"domain\":\"Revenue cycle\"}","purpose":"Stages claim financial transaction line items including charges, payments, and transfers.","columns":["claim_transaction_id","claim_id","charge_id","patient_id","transaction_type","amount","payment_method","service_start_at","service_end_at","place_of_service","procedure_code","modifier1","modifier2","diagnosisref1","diagnosisref2","diagnosisref3","diagnosisref4","units","department_id","notes","unit_amount","transfer_out_id","transfer_type","payments","adjustments","outstanding","encounter_id","patient_insurance_id","provider_id","supervising_provider_id","ingested_at","source_system","row_hash"],"tests":{"claim_transaction_id":["unique","not_null"]}},
  {"name":"stg_claims","layer":"staging","tags":"{\"layer\":\"silver\",\"dbt_layer\":\"staging\",\"domain\":\"Revenue cycle\"}","purpose":"Stages claim headers with diagnoses, statuses, and outstanding balances.","columns":["claim_id","patient_id","provider_id","primary_insurance_id","secondary_insurance_id","department_id","patient_department_id","diagnosis1","diagnosis2","diagnosis3","diagnosis4","diagnosis5","diagnosis6","diagnosis7","diagnosis8","encounter_id","illness_onset_at","service_at","supervising_provider_id","status_primary","status_secondary","status_patient","outstanding_primary","outstanding_secondary","outstanding_patient","ingested_at","source_system","row_hash"],"tests":{"claim_id":["unique","not_null"]}},
  {"name":"stg_careplans","layer":"staging","tags":"{\"layer\":\"silver\",\"dbt_layer\":\"staging\",\"domain\":\"Clinical\"}","purpose":"Stages patient care plan records with an active-status flag.","columns":["care_plan_id","care_plan_start_date","care_plan_end_date","patient_id","encounter_id","care_plan_code","care_plan_description","reason_code","reason_description","is_active","ingested_at","source_system","row_hash"]},
  {"name":"int_patient_demographics","layer":"intermediate","tags":"{\"layer\":\"silver\",\"dbt_layer\":\"intermediate\",\"domain\":\"Patient\"}","purpose":"Derives patient age, mortality flag, and age-band segmentation from staged patients.","columns":["patient_id","birth_date","death_date","first_name","last_name","gender","race","ethnicity","city","state","zip","annual_income","lifetime_healthcare_expenses","lifetime_coverage_amount","is_alive","age_years","age_band"]},
  {"name":"int_observations_vitals","layer":"intermediate","tags":"{\"layer\":\"silver\",\"dbt_layer\":\"intermediate\",\"domain\":\"Clinical\"}","purpose":"Filters vital-sign observations and casts values to numeric where parseable.","columns":["patient_id","encounter_id","observation_at","observation_code","observation_description","observation_value_numeric","units"]},
  {"name":"int_latest_vitals","layer":"intermediate","tags":"{\"layer\":\"silver\",\"dbt_layer\":\"intermediate\",\"domain\":\"Clinical\"}","purpose":"Returns the most recent vital-sign reading per patient and observation code.","columns":["patient_id","encounter_id","observation_at","observation_code","observation_description","observation_value_numeric","units","recency_rank"]},
  {"name":"int_patient_active_conditions","layer":"intermediate","tags":"{\"layer\":\"silver\",\"dbt_layer\":\"intermediate\",\"domain\":\"Clinical\"}","purpose":"Aggregates active conditions per patient into a count and description set.","columns":["patient_id","active_condition_count","active_condition_descriptions"]},
  {"name":"int_encounter_clinical_counts","layer":"intermediate","tags":"{\"layer\":\"silver\",\"dbt_layer\":\"intermediate\",\"domain\":\"Operations\"}","purpose":"Rolls up clinical activity counts and costs per encounter across clinical domains.","columns":["encounter_id","patient_id","condition_count","procedure_count","procedure_cost","observation_count","medication_count","medication_cost","immunization_count"]},
  {"name":"int_claim_financials","layer":"intermediate","tags":"{\"layer\":\"silver\",\"dbt_layer\":\"intermediate\",\"domain\":\"Revenue cycle\"}","purpose":"Aggregates claim transaction lines into charge, payment, transfer, and balance metrics.","columns":["claim_id","patient_id","transaction_line_count","total_charges","total_payments","total_transfer_out","total_transfer_in","max_outstanding","first_service_date","last_service_date"]},
  {"name":"int_claims_enriched","layer":"intermediate","tags":"{\"layer\":\"silver\",\"dbt_layer\":\"intermediate\",\"domain\":\"Revenue cycle\"}","purpose":"Enriches claims with encounter class, dates, and organization from encounters.","columns":["claim_id","patient_id","provider_id","encounter_id","service_at","service_date","status_primary","status_secondary","outstanding_primary","outstanding_secondary","diagnosis1","diagnosis2","diagnosis3","encounter_class","encounter_start_date","organization_id"]},
  {"name":"int_claims_with_financials","layer":"intermediate","tags":"{\"layer\":\"silver\",\"dbt_layer\":\"intermediate\",\"domain\":\"Revenue cycle\"}","purpose":"Joins enriched claims with aggregated financials and computes net balance.","columns":["claim_id","patient_id","provider_id","encounter_id","service_at","service_date","status_primary","status_secondary","outstanding_primary","outstanding_secondary","diagnosis1","diagnosis2","diagnosis3","encounter_class","encounter_start_date","organization_id","transaction_line_count","total_charges","total_payments","total_transfer_out","total_transfer_in","max_outstanding","net_balance"]},
  {"name":"int_encounters_enriched","layer":"intermediate","tags":"{\"layer\":\"silver\",\"dbt_layer\":\"intermediate\",\"domain\":\"Operations\"}","purpose":"Enriches encounters with patient demographics, provider, organization, and payer context.","columns":["encounter_id","patient_id","provider_id","organization_id","payer_id","encounter_class","encounter_code","encounter_description","encounter_start_date","encounter_start_at","encounter_end_at","encounter_duration_minutes","base_encounter_cost","total_claim_cost","payer_coverage_amount","reason_code","reason_description","age_years","age_band","patient_gender","patient_state","is_alive","provider_name","provider_specialty","organization_name","org_city","org_state","payer_name","payer_ownership"]},
  {"name":"dim_patients","layer":"marts","tags":"{\"layer\":\"gold\",\"dbt_layer\":\"marts\",\"domain\":\"Patient\"}","purpose":"Gold patient dimension exposing derived demographics for analytics and joins.","columns":["patient_id","birth_date","death_date","first_name","last_name","gender","race","ethnicity","city","state","zip","annual_income","lifetime_healthcare_expenses","lifetime_coverage_amount","is_alive","age_years","age_band"],"tests":{"patient_id":["unique","not_null"]}},
  {"name":"dim_providers","layer":"marts","tags":"{\"layer\":\"gold\",\"dbt_layer\":\"marts\",\"domain\":\"Operations\"}","purpose":"Gold provider dimension with location and lifetime activity metrics.","columns":["provider_id","organization_id","provider_name","gender","specialty","city","state","zip","lifetime_encounters","lifetime_procedures"]},
  {"name":"dim_organizations","layer":"marts","tags":"{\"layer\":\"gold\",\"dbt_layer\":\"marts\",\"domain\":\"Operations\"}","purpose":"Gold organization dimension with geolocation and utilization attributes.","columns":["organization_id","organization_name","address","city","state","zip","latitude","longitude","phone","revenue","utilization"]},
  {"name":"dim_payers","layer":"marts","tags":"{\"layer\":\"gold\",\"dbt_layer\":\"marts\",\"domain\":\"Revenue cycle\"}","purpose":"Gold payer dimension with coverage and membership financial attributes.","columns":["payer_id","payer_name","ownership","amount_covered","amount_uncovered","revenue","covered_encounters","uncovered_encounters","unique_customers","quality_of_life_avg","member_months"]},
  {"name":"fct_encounters","layer":"marts","tags":"{\"layer\":\"gold\",\"dbt_layer\":\"marts\",\"domain\":\"Operations\"}","purpose":"Gold encounter fact table with full enriched context for encounter-level analysis.","columns":["encounter_id","patient_id","provider_id","organization_id","payer_id","encounter_class","encounter_code","encounter_description","encounter_start_date","encounter_start_at","encounter_end_at","encounter_duration_minutes","base_encounter_cost","total_claim_cost","payer_coverage_amount","reason_code","reason_description","age_years","age_band","patient_gender","patient_state","is_alive","provider_name","provider_specialty","organization_name","org_city","org_state","payer_name","payer_ownership"],"tests":{"encounter_id":["unique","not_null"],"patient_id":["not_null","relationships"]}},
  {"name":"fct_claims","layer":"marts","tags":"{\"layer\":\"gold\",\"dbt_layer\":\"marts\",\"domain\":\"Revenue cycle\"}","purpose":"Gold claim fact combining enriched claim attributes with financial aggregates.","columns":["claim_id","patient_id","provider_id","encounter_id","service_at","service_date","status_primary","status_secondary","outstanding_primary","outstanding_secondary","diagnosis1","diagnosis2","diagnosis3","encounter_class","encounter_start_date","organization_id","transaction_line_count","total_charges","total_payments","total_transfer_out","total_transfer_in","max_outstanding","net_balance"],"tests":{"claim_id":["unique","not_null"]}},
  {"name":"fct_claim_transactions","layer":"marts","tags":"{\"layer\":\"gold\",\"dbt_layer\":\"marts\",\"domain\":\"Revenue cycle\"}","purpose":"Gold claim transaction fact for revenue-cycle line-item analysis.","columns":["claim_transaction_id","claim_id","patient_id","encounter_id","provider_id","transaction_type","amount","payment_method","service_date","service_start_at","service_end_at","procedure_code","department_id","payments","adjustments","outstanding","notes"]},
  {"name":"fct_conditions","layer":"marts","tags":"{\"layer\":\"gold\",\"dbt_layer\":\"marts\",\"domain\":\"Clinical\"}","purpose":"Gold condition fact table at diagnosis grain for clinical analytics.","columns":["condition_start_date","condition_end_date","patient_id","encounter_id","code_system","condition_code","condition_description","is_active","ingested_at","source_system","row_hash"]},
  {"name":"fct_procedures","layer":"marts","tags":"{\"layer\":\"gold\",\"dbt_layer\":\"marts\",\"domain\":\"Clinical\"}","purpose":"Gold procedure fact table at procedure-event grain.","columns":["procedure_start_at","procedure_end_at","patient_id","encounter_id","code_system","procedure_code","procedure_description","base_cost","reason_code","reason_description","ingested_at","source_system","row_hash"]},
  {"name":"fct_medications","layer":"marts","tags":"{\"layer\":\"gold\",\"dbt_layer\":\"marts\",\"domain\":\"Clinical\"}","purpose":"Gold medication fact table at prescription grain.","columns":["medication_start_at","medication_end_at","patient_id","payer_id","encounter_id","medication_code","medication_description","base_cost","payer_coverage_amount","dispenses","total_cost","reason_code","reason_description","is_active","ingested_at","source_system","row_hash"]},
  {"name":"fct_observations","layer":"marts","tags":"{\"layer\":\"gold\",\"dbt_layer\":\"marts\",\"domain\":\"Clinical\"}","purpose":"Gold observation fact table at observation grain.","columns":["observation_at","patient_id","encounter_id","observation_category","observation_code","observation_description","observation_value","units","value_type","ingested_at","source_system","row_hash"]},
  {"name":"fct_immunizations","layer":"marts","tags":"{\"layer\":\"gold\",\"dbt_layer\":\"marts\",\"domain\":\"Clinical\"}","purpose":"Gold immunization fact table at dose-administration grain.","columns":["immunization_at","patient_id","encounter_id","immunization_code","immunization_description","base_cost","ingested_at","source_system","row_hash"]},
  {"name":"fct_allergies","layer":"marts","tags":"{\"layer\":\"gold\",\"dbt_layer\":\"marts\",\"domain\":\"Clinical\"}","purpose":"Gold allergy fact table at allergy-record grain.","columns":["allergy_start_date","allergy_end_date","patient_id","encounter_id","allergy_code","code_system","allergy_description","allergy_type","allergy_category","is_active","ingested_at","source_system","row_hash"]},
  {"name":"fct_care_plans","layer":"marts","tags":"{\"layer\":\"gold\",\"dbt_layer\":\"marts\",\"domain\":\"Clinical\"}","purpose":"Gold care plan fact table at care-plan grain.","columns":["care_plan_id","care_plan_start_date","care_plan_end_date","patient_id","encounter_id","care_plan_code","care_plan_description","reason_code","reason_description","is_active","ingested_at","source_system","row_hash"]},
  {"name":"fct_imaging_studies","layer":"marts","tags":"{\"layer\":\"gold\",\"dbt_layer\":\"marts\",\"domain\":\"Clinical\"}","purpose":"Gold imaging study fact table at DICOM instance grain.","columns":["imaging_study_id","study_at","patient_id","encounter_id","series_uid","bodysite_code","bodysite_description","modality_code","modality_description","instance_uid","sop_code","sop_description","procedure_code","ingested_at","source_system","row_hash"]},
  {"name":"mart_patient_summary","layer":"marts","tags":"{\"layer\":\"gold\",\"dbt_layer\":\"marts\",\"domain\":\"Patient\"}","purpose":"One row per patient combining demographics, utilization, conditions, and financial rollups.","columns":["patient_id","birth_date","death_date","first_name","last_name","gender","race","ethnicity","city","state","zip","annual_income","lifetime_healthcare_expenses","lifetime_coverage_amount","is_alive","age_years","age_band","encounter_count","distinct_encounter_classes","first_encounter_date","last_encounter_date","total_encounter_claim_cost","total_base_encounter_cost","active_condition_count","claim_count","lifetime_charges","lifetime_payments"],"tests":{"patient_id":["unique","not_null"]}},
  {"name":"mart_encounter_cost_analysis","layer":"marts","tags":"{\"layer\":\"gold\",\"dbt_layer\":\"marts\",\"domain\":\"Operations\"}","purpose":"Encounter-level cost analysis joined with clinical activity counts.","columns":["encounter_id","patient_id","encounter_class","encounter_start_date","organization_name","provider_name","payer_name","base_encounter_cost","total_claim_cost","payer_coverage_amount","condition_count","procedure_count","procedure_cost","medication_count","medication_cost","observation_count"]},
  {"name":"mart_provider_panel","layer":"marts","tags":"{\"layer\":\"gold\",\"dbt_layer\":\"marts\",\"domain\":\"Operations\"}","purpose":"Provider panel metrics aggregating encounters, patients, costs, and duration.","columns":["provider_id","provider_name","specialty","organization_id","organization_name","encounter_count","distinct_patients","total_claim_cost","avg_encounter_minutes"]},
  {"name":"mart_organization_utilization","layer":"marts","tags":"{\"layer\":\"gold\",\"dbt_layer\":\"marts\",\"domain\":\"Operations\"}","purpose":"Organization utilization summary with encounter volume and claim costs.","columns":["organization_id","organization_name","city","state","reported_utilization","encounter_count","distinct_patients","distinct_providers","total_claim_cost"]},
  {"name":"mart_payer_financials","layer":"marts","tags":"{\"layer\":\"gold\",\"dbt_layer\":\"marts\",\"domain\":\"Revenue cycle\"}","purpose":"Payer financial summary linking payer attributes to encounter and medication coverage.","columns":["payer_id","payer_name","ownership","amount_covered","amount_uncovered","revenue","encounter_count","total_payer_coverage_on_encounters","total_medication_coverage"]},
  {"name":"mart_population_health","layer":"marts","tags":"{\"layer\":\"gold\",\"dbt_layer\":\"marts\",\"domain\":\"Population\"}","purpose":"Population health cohort metrics grouped by age band, gender, and state.","columns":["age_band","gender","state","patient_count","alive_count","avg_age","avg_lifetime_expenses","avg_annual_income"]},
  {"name":"mart_revenue_cycle","layer":"marts","tags":"{\"layer\":\"gold\",\"dbt_layer\":\"marts\",\"domain\":\"Revenue cycle\"}","purpose":"Revenue-cycle summary aggregating claim transactions by transaction type.","columns":["transaction_type","line_count","total_amount","distinct_claims","distinct_patients"]},
  {"name":"mart_chronic_conditions","layer":"marts","tags":"{\"layer\":\"gold\",\"dbt_layer\":\"marts\",\"domain\":\"Clinical\"}","purpose":"Condition prevalence report with patient and active-record counts per diagnosis.","columns":["condition_code","condition_description","patient_count","record_count","active_record_count"]},
  {"name":"mart_medication_utilization","layer":"marts","tags":"{\"layer\":\"gold\",\"dbt_layer\":\"marts\",\"domain\":\"Clinical\"}","purpose":"Medication utilization and cost summary grouped by drug code.","columns":["medication_code","medication_description","prescription_count","patient_count","total_cost","total_payer_coverage","avg_dispenses"]},
  {"name":"mart_immunization_coverage","layer":"marts","tags":"{\"layer\":\"gold\",\"dbt_layer\":\"marts\",\"domain\":\"Population\"}","purpose":"Immunization coverage summary with dose and patient counts per vaccine.","columns":["immunization_code","immunization_description","dose_count","patient_count","total_cost"]},
  {"name":"mart_encounter_class_distribution","layer":"marts","tags":"{\"layer\":\"gold\",\"dbt_layer\":\"marts\",\"domain\":\"Population\"}","purpose":"Encounter volume and cost distribution by encounter class.","columns":["encounter_class","encounter_count","patient_count","avg_duration_minutes","total_claim_cost","avg_claim_cost"]},
  {"name":"mart_imaging_by_modality","layer":"marts","tags":"{\"layer\":\"gold\",\"dbt_layer\":\"marts\",\"domain\":\"Clinical\"}","purpose":"Imaging volume summary grouped by modality and body site.","columns":["modality_code","modality_description","bodysite_description","instance_count","patient_count","encounter_count"]},
  {"name":"mart_vital_signs_latest","layer":"marts","tags":"{\"layer\":\"gold\",\"dbt_layer\":\"marts\",\"domain\":\"Patient\"}","purpose":"Latest vital-sign values per patient for clinical dashboards.","columns":["patient_id","observation_code","observation_description","observation_value_numeric","units","observation_at"]},
  {"name":"mart_claims_aging","layer":"marts","tags":"{\"layer\":\"gold\",\"dbt_layer\":\"marts\",\"domain\":\"Revenue cycle\"}","purpose":"Claims aging summary by primary status with outstanding balance metrics.","columns":["status_primary","claim_count","total_outstanding","avg_outstanding"]},
  {"name":"mart_allergy_registry","layer":"marts","tags":"{\"layer\":\"gold\",\"dbt_layer\":\"marts\",\"domain\":\"Clinical\"}","purpose":"Patient allergy registry with key clinical attributes for safety reporting.","columns":["patient_id","allergy_code","allergy_description","allergy_category","allergy_type","allergy_start_date","is_active"]},
  {"name":"mart_care_plan_registry","layer":"marts","tags":"{\"layer\":\"gold\",\"dbt_layer\":\"marts\",\"domain\":\"Clinical\"}","purpose":"Care plan registry for care-management and coordination reporting.","columns":["care_plan_id","care_plan_start_date","care_plan_end_date","patient_id","encounter_id","care_plan_code","care_plan_description","reason_code","reason_description","is_active","ingested_at","source_system","row_hash"]},
  {"name":"mart_patient_coverage_timeline","layer":"marts","tags":"{\"layer\":\"gold\",\"dbt_layer\":\"marts\",\"domain\":\"Patient\"}","purpose":"Patient insurance coverage timeline with date-bounded payer transitions.","columns":["patient_id","payer_id","member_id","coverage_start_date","coverage_end_date","plan_ownership","owner_name"]},
  {"name":"mv_revenue_cycle_kpis","layer":"marts","tags":"{\"layer\":\"gold\",\"dbt_layer\":\"marts\",\"domain\":\"Revenue cycle\"}","purpose":"Materialized-view BI layer for revenue-cycle KPIs with network share and ranking.","columns":["transaction_type","line_count","total_amount","distinct_claims","distinct_patients","avg_amount_per_line","pct_of_network_amount","amount_rank"]},
  {"name":"mv_encounter_volume_by_class","layer":"marts","tags":"{\"layer\":\"gold\",\"dbt_layer\":\"marts\",\"domain\":\"Population\"}","purpose":"Materialized-view BI layer for encounter mix by class with share-of-total and rank.","columns":["encounter_class","encounter_count","patient_count","avg_duration_minutes","total_claim_cost","avg_claim_cost","pct_of_encounters","encounter_volume_rank"]}
]
""")


def col_description(name: str) -> str:
    if name in COL_DESC:
        return COL_DESC[name]
    readable = name.replace("_", " ")
    return f"{readable.capitalize()}."


def yaml_quote(value: str) -> str:
    return json.dumps(value)


def render_column(name: str, tests: list | None = None) -> list[str]:
    lines = [
        f"      - name: {name}",
        f"        description: {yaml_quote(col_description(name))}",
    ]
    if not tests:
        return lines

    if tests == ["unique", "not_null"]:
        lines.append("        tests: [unique, not_null]")
    elif tests == ["not_null"]:
        lines.append("        tests: [not_null]")
    elif tests == ["not_null", "relationships"]:
        lines.extend(
            [
                "        tests:",
                "          - not_null",
                "          - relationships:",
                "              arguments:",
                "                to: ref('dim_patients')",
                "                field: patient_id",
            ]
        )
    else:
        lines.append(f"        tests: {json.dumps(tests)}")
    return lines


def render_model(model: dict) -> list[str]:
    lines = [
        f"  - name: {model['name']}",
        f"    description: {yaml_quote(model['purpose'])}",
        "    config:",
        f"      query_tags: '{model['tags']}'",
        "    columns:",
    ]
    tests = model.get("tests", {})
    for col in model["columns"]:
        col_tests = tests.get(col)
        lines.extend(render_column(col, col_tests))
    return lines


def write_layer(layer: str, filename: str) -> None:
    models = [m for m in MODELS if m["layer"] == layer]
    content = ["version: 2", "", "models:"]
    for model in models:
        content.extend(render_model(model))
        content.append("")
    path = ROOT / "models" / layer / filename
    path.write_text("\n".join(content).rstrip() + "\n", encoding="utf-8")
    print(f"Wrote {path} ({len(models)} models)")


if __name__ == "__main__":
    write_layer("staging", "_staging.yml")
    write_layer("intermediate", "_intermediate.yml")
    write_layer("marts", "_marts.yml")
